apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: instavote
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: back
      app: postgres
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: postgres
        role: db
        tier: back
        version: "9.4"
    spec:
      containers:
      - image: postgres:9.4
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name:  POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
 
        imagePullPolicy: Always
        
        name: db
        ports:
        - containerPort: 5432
          protocol: TCP
