apiVersion: v1
kind: Pod
metadata:
  name: vote
  namespace: instavote
  labels:
    app: python
    role: vote
    version: v1
spec:
  containers:
    - name: app
      image: schoolofdevops/vote:v1
