apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: instavote
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  revisionHistoryLimit: 4
  paused: false
  replicas: 2
  minReadySeconds: 20
  selector:
    matchLabels:
      role: worker
    matchExpressions:
      - {key: version, operator: In, values: [v1, v2, latest]}
  template:
    metadata:
      name: worker
      labels:
        app: java
        role: worker
        version: latest
    spec:
      containers:
        - name: app
          image: schoolofdevops/vote-worker:latest
