---
apiVersion: v1
kind: Service
metadata:
  name: deploymnt-web-server-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80